CREATE TABLE IF NOT EXISTS "TRANSACTION" (
    ID INT NOT NULL PRIMARY KEY,
    OCCURRED_ON DATE NOT NULL,
    DESCRIPTION VARCHAR(512) NOT NULL,
    ACCOUNT INT NOT NULL,
    TYPE VARCHAR(16) NOT NULL,
    AMOUNT NUMERIC(19, 4) NOT NULL,
    CATEGORY INT NOT NULL,
    NOTES VARCHAR(8192),
    VERSION BIGINT
);