name: Build

on: [ push, pull_request ]
jobs:

  mongodb-atlas-setup:
    uses: ./.github/workflows/mongodb-atlas-setup.yml
    with:
      project-name: bookkeeper-test-${{github.run_number}}
      cluster-name: bookkeeper-cluster
      username: user
      password: ac85Z15d2d481Qr7
    secrets: inherit

  build:
    runs-on: ubuntu-latest
    needs: mongodb-atlas-setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin

      - name: Get the public IP of this runner
        id: get_gh_runner_ip
        shell: bash
        run: echo "ip_address=$(curl https://checkip.amazonaws.com)" >> "$GITHUB_OUTPUT"
      - name: Setup AtlasCLI
        uses: mongodb/atlas-github-action@v0.2.0
      - name: Add runner IP to MongoDB access list
        shell: bash
        run: atlas accessLists create ${{ steps.get_gh_runner_ip.outputs.ip_address }} --type ipAddress --projectId ${{ needs.mongodb-atlas-setup.output.project-id }}
        env:
          MONGODB_ATLAS_PUBLIC_API_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_API_KEY }}
          MONGODB_ATLAS_PRIVATE_API_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_API_KEY }}
          MONGODB_ATLAS_ORG_ID: ${{ secrets.MONGODB_ATLAS_ORG_ID }}
          MONGODB_ATLAS_PROJECT_ID: ${{ secrets.MONGODB_ATLAS_PROJECT_ID }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      - run: ./gradlew buildK
        env:
          SPRING_PROFILES_ACTIVE: test
          MONGODB_ATLAS_CONNECTION_STRING: ${{ needs.mongodb-atlas-setup.outputs.connection-string }}
      - run: ./gradlew jacocoTestReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  mongodb-atlas-teardown:
    if: always()
    needs:
      - mongodb-atlas-setup
      - build
    uses: ./.github/workflows/mongodb-atlas-teardown.yml
    with:
      project-id: ${{ needs.mongodb-atlas-setup.outputs.project-id }}
      cluster-name: bookkeeper-cluster
    secrets: inherit
