name: CoverageReport

on:
  workflow_call:
    inputs:
      report_name:
        required: true
        type: string
      report_path:
          required: true
          type: string

jobs:
  upload-codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.report_name }}
          path: ${{ inputs.report_path }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          fail_ci_if_error: true
          flags: '--nonZero'
